// One Caddy site block per project renting web, written to var/routes/web.caddy
// and imported at the TOP LEVEL of var/Caddyfile — site blocks cannot nest, so
// this file cannot live inside another host's block.
//
// An archived project's origin is not served at all: the name stops resolving to
// anything here and the browser gets a plain connection error rather than a page
// pretending the experiment is still alive. Its catalog page stays and explains.
import { normalizeHttpUrl } from "../../lib/registry.mjs";

export default function routes(entries) {
  const out = ["# generated by `labs render` from var/projects/*/realized.json — do not edit"];
  for (const e of entries) {
    const w = e.rented?.web;
    if (!w || e.status === "archived") continue;
    const host = new URL(normalizeHttpUrl(w.origin, { field: `web origin for ${e.id}` })).host;

    const body = w.root
      ? `\troot * ${w.root}\n\tencode zstd gzip\n${w.spa ? "\ttry_files {path} {path}/ /index.html\n" : ""}\tfile_server`
      : `\treverse_proxy 127.0.0.1:${w.port}`;

    // Each project is its own origin, so these headers are per project — and
    // frame-ancestors is denied by default: an experiment should not be
    // embeddable into someone else's page without asking.
    out.push(`${host} {\n${body}\n\theader {\n\t\tX-Content-Type-Options nosniff\n\t\tReferrer-Policy strict-origin-when-cross-origin\n\t\tX-Frame-Options DENY\n\t\t-Server\n\t}\n}`);
  }
  return out.join("\n") + "\n";
}
