// One Caddy `handle` per project renting mcp, written to var/routes/mcp.caddy and
// imported inside the mcp.abclegacyllc.com block. Caddy orders `handle` blocks by
// path length, so the gateway's catch-all always comes last no matter what.
//
// A `building` project is routed (its author has to test it) but not indexed;
// an `archived` one is not routed at all — the request falls through to the
// gateway, which answers 410 with the note.
import { normalizeHttpUrl } from "../../lib/registry.mjs";

export default function routes(entries) {
  const out = ["# generated by `labs render` from var/registry.d — do not edit"];
  for (const e of entries) {
    const r = e.rented?.mcp;
    if (!r || e.status === "archived") continue;
    if (r.upstream) {
      // Validated and normalized first, so nothing unparsed ever reaches Caddy. The
      // address Caddy gets is the ORIGIN — scheme, host, port — because a proxy
      // upstream may not carry a path, and URL normalization adds a trailing "/".
      const url = new URL(normalizeHttpUrl(r.upstream, { externalOnly: true, field: `mcp upstream for ${e.id}` }));
      out.push(`handle ${r.path}* {\n\treverse_proxy ${url.origin} {\n\t\theader_up Host ${url.host}\n\t}\n}`);
    } else if (e.assigned?.port) {
      out.push(`handle ${r.path}* {\n\treverse_proxy 127.0.0.1:${e.assigned.port}\n}`);
    }
  }
  return out.join("\n") + "\n";
}
