// One Caddy `handle` per project renting mcp, written to var/routes/mcp.caddy and
// imported inside the mcp.abclegacyllc.com block. Caddy orders `handle` blocks by
// path length, so the gateway's catch-all always comes last no matter what.
//
// A `building` project is routed (its author has to test it) but not indexed;
// an `archived` one is not routed at all — the request falls through to the
// gateway, which answers 410 with the note.
export default function routes(entries) {
  const out = ["# generated by `labs render` from var/registry.d — do not edit"];
  for (const e of entries) {
    const r = e.rented?.mcp;
    if (!r || e.status === "archived") continue;
    if (r.upstream) {
      const host = new URL(r.upstream).host;
      out.push(`handle ${r.path}* {\n\treverse_proxy ${r.upstream} {\n\t\theader_up Host ${host}\n\t}\n}`);
    } else if (e.assigned?.port) {
      out.push(`handle ${r.path}* {\n\treverse_proxy 127.0.0.1:${e.assigned.port}\n}`);
    }
  }
  return out.join("\n") + "\n";
}
